version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: guildapi
    restart: always
    networks:
      - traefik
      - randosoru_net
      - redive_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.randosoru-server.rule=(Host(`${APP_DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/socket.io`)))"
      - "traefik.http.routers.randosoru-server.entrypoints=websecure"
      - "traefik.http.routers.randosoru-server.tls=true"
      - "traefik.http.routers.randosoru-server.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"

  frontend:
    build:
      context: ../Randosoru-React
      dockerfile: Dockerfile
    networks:
      - traefik
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.randosoru-web.rule=Host(`${APP_DOMAIN}`)"
      - "traefik.http.routers.randosoru-web.entrypoints=websecure"
      - "traefik.http.routers.randosoru-web.tls=true"
      - "traefik.http.routers.randosoru-web.tls.certresolver=leresolver"
      - "traefik.docker.network=traefik"

  mysql:
    image: mysql:latest
    container_name: randosoru_mysql
    restart: always
    networks:
      - randosoru_net
    environment:
      - MYSQL_DATABASE=Guild_Randosoru
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"

volumes:
  mysql_data:


networks:
  traefik:
    external: true
  randosoru_net:
  redive_net:
    external: true
